### ISSUE TITLE
Clair's path towards DockerHub independence

### ISSUE THREAD

**Issue by jan-zmeskal** [quay/clair#1156]
### Introduction

DockerHub introduced [pull rate limits](https://www.docker.com/increase-rate-limits) in November 2020, which is especially hurtful for CI workflows. If they run many times a day, they might easily hit it. Therefore I propose that we change our CI so that it does not rely on docker.io/golang image any more. 

### Implementation
After discussing this topic with Louis and Hank, we came to the conclusion that we can build our own golang image. We already do that for local development anyway. Of course, if custom golang image is to become the basis of our official clair image, it needs to be well maintained by means of automation. We discussed how to do that and settled on regularly scheduled GitHub action that checks golang version and build and build a new custom golang image if new golang version has been released since our last build.

### Tasks
- [x] As of now, our custom golang image resides in quay.io/organization/claircore, we should move it to quay.io/organization/projectquay. All code that depends on quay.io/claircore/golang must be changed accordingly.
- [x] Have an authoritative list of major golang releases that we test with (as of time of me writing this, it's 1.13, 1.14, 1.15).
- [x] Set up regular GH action that tracks golang releases, possibly by means of GH API tracking golang tags as suggested by Hank. Other option might be tracking changes in DockerHub golang repository. But that seems unnecessarily indirect.
- [x] GH action persists information about latest golang releases, possibly in artifact as suggested by Louis
- [x] The regular GH action checks if our golang image's tags are up to date with golang releases. If not, it builds and pushes tags that are behind.
- [x] All code that relies on docker.io/golang is changed so that it uses quay.io/projectquay/golang instead. I created https://github.com/quay/claircore/pull/284 and https://github.com/quay/clair/pull/1147 before this plan which might be used for reference.
- [x] We need to figure out whether we can do this with one Dockerfile (I think we can, because it can be provided build args) or we need to template several Dockerfiles
- [x] We need to figure out whether a separate directory should be set up for this or whether this automation can live in this repo

### Notes:
- In case we need to persists some information between the runs, `actions/download-artifact@v2` can't really be used for that purpose. However, we might be able to fetch previously build artifacts using [REST API](https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#artifacts).

**Comment by jan-zmeskal** [comment]
@ldelossa @hdonnay Please review my proposal and check that I haven't forgotten anything major. Also, please let's treat this issue as the main discussion platform for this effort from now on.

**Comment by ldelossa** [comment]
@jan-zmeskal does this pr currently reflect all the tasks as "done" ?

**Comment by jan-zmeskal** [comment]
@ldelossa With my current PR merged, we'll still have points Nr. 2 and 6 still pending. I'd like to tackle them in separate PRs. I still don't know if Nr. 2 is possible. But the idea here is to have one authoritative set of Go releases that we support and and would be used by all our workflow. At this point, each workflow has its own list with supported versions. Since this affect more workflows and is not essential for this to work, I'd like to keep it as separate PR. Nr. 6 should be quite easy, but I think it'd be useful too see that the new workflow has been running successfully for a couple of days before we fully switch to quay.io/projectquay/golang in our CI.
